In [2]:
import numpy as np
N = 10
A = np.zeros((N,N))
A_1 = np.zeros((N,N))
A_1[0:5, 0:5] = np.arange(10, 5, -1)
print(A)
print(A_1)
H = 10
A_2 = np.zeros((N,N))
for k in range(N):
  A_2[:N-k,k] = H
  H -= 1
print(A_2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[10.  9.  8.  7.  6.  0.  0.  0.  0.  0.]
 [10.  9.  8.  7.  6.  0.  0.  0.  0.  0.]
 [10.  9.  8.  7.  6.  0.  0.  0.  0.  0.]
 [10.  9.  8.  7.  6.  0.  0.  0.  0.  0.]
 [10.  9.  8.  7.  6.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
 [10.  9.  8.  7.  6.  5.  4.  3.  2.  0.]
 [10.  9.  8.  7.  6.  5.  4.  3.  0.  0.]
 [10.  9.  8.  7.  6.  5.  4.  0.  0.  0.]
 [10.  9.  8.  7.  6.  5.  0.  0.  0.  0.]
 [10.  9.  8.  7.  6.  