In [7]:
import numpy as np

A=np.array([[5., 0., 0., 0., 0.],
   [5., 4., 0., 0., 0.],
   [5., 4., 3., 0., 0.],
   [5., 4., 3., 2., 0.],
   [5., 4., 3., 2., 0.]])

A[2, :]=0

print(A)

[[5. 0. 0. 0. 0.]
 [5. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [5. 4. 3. 2. 0.]
 [5. 4. 3. 2. 0.]]
