In [3]:
import numpy as np

In [8]:
import numpy as np

# Размер матрицы
N = 10

# Шаг 1: создаём нулевую матрицу 10×10
A = np.zeros((N, N), dtype=int)

# Шаг 2: заполняем первую часть (первые 5 столбцов) во всех строках
for i in range(N):
    A[i, 0:5] = [10, 9, 8, 7, 6]

# Шаг 3: заполняем по строкам вторую часть
for i in range(N):
    if i == 0:
        A[i, 5] = 1
    elif i == 1:
        A[i, 5:7] = 2
    elif i == 2:
        A[i, 5:8] = 3
    elif i == 3:
        A[i, 5:9] = 4
    elif i == 4:
        A[i, 5:10] = 5
    elif i == 5:
        # все нули, ничего не делаем
        pass
    elif i == 6:
        A[i, 4] = 0  # убираем 7
    elif i == 7:
        A[i, 3] = 0  # убираем 8
        A[i, 4] = 0
    elif i == 8:
        A[i, 2] = 0  # убираем 9
        A[i, 3] = 0
        A[i, 4] = 0
    elif i == 9:
        A[i, 1] = 0  # убираем 10? Но там 10 остаётся
        A[i, 2] = 0
        A[i, 3] = 0
        A[i, 4] = 0

# Шаг 4: вывод результата
print("Матрица для варианта 9 (исправленная):")
print(A)

Матрица для варианта 9 (исправленная):
[[10  9  8  7  6  1  0  0  0  0]
 [10  9  8  7  6  2  2  0  0  0]
 [10  9  8  7  6  3  3  3  0  0]
 [10  9  8  7  6  4  4  4  4  0]
 [10  9  8  7  6  5  5  5  5  5]
 [10  9  8  7  6  0  0  0  0  0]
 [10  9  8  7  0  0  0  0  0  0]
 [10  9  8  0  0  0  0  0  0  0]
 [10  9  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]]
